language: cpp
dist: bionic
compiler:
  - gcc

os:
  - linux
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-8
      - libglm-dev
      - libglew2.0
      - libglew-dev
      - libsdl2-2.0.0
      - libsdl2-dev
      - libdevil1c2
      - libdevil-dev
      - libcairo2
      - libcairo2-dev
      - libyaml-0-2
      - libyaml-dev
      
env:
  - CXX=g++-8

script:
  - wget -c http://mirrors.kernel.org/ubuntu/pool/universe/f/fmtlib/libfmt-dev_5.2.1+ds-2_amd64.deb
  - sudo dpkg -i libfmt-dev_5.2.1+ds-2_amd64.deb
  - ${CXX} --version
  - mkdir build && cd build
  - cmake -DDO_TESTS=on -DDO_CHECK_ASAN=off -DSET_COVERAGE=off -DUSE_RELATIVE_PATH=on -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - make familyline-tests
  - ./familyline-tests
