language: cpp
dist: xenial
sudo: required
compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-7
      - libglm-dev
      - libglew1.10
      - libglew-dev
      - libsdl2-2.0.0
      - libsdl2-dev
      - libdevil1c2
      - libdevil-dev
      - libcairo2
      - libcairo2-dev
      - libyaml-0-2
      - libyaml-dev

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

#
# We need to download a newer version of glm manually, because travis only support
# ubuntu until 16.04, and that version ships with a glm without a pkgconfig entry
# Without that, we don't have a reliable way of finding glm.
# This is fixed in 18.04. We'll wait until travis support this version
#
before_install:
  - wget -c https://github.com/fmtlib/fmt/archive/5.2.1.tar.gz
  - tar zxvf 5.2.1.tar.gz && mv fmt-5.2.1 fmt
  - wget -c https://launchpad.net/ubuntu/+archive/primary/+files/libglm-dev_0.9.9~a2-2_all.deb
  - sudo dpkg -i libglm-dev_0.9.9~a2-2_all.deb

script:
  - eval "${MATRIX_EVAL}"
  - cmake -DDO_TESTS=on -DDO_CHECK_ASAN=off -DSET_COVERAGE=off -DUSE_RELATIVE_PATH=on -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
  - make familyline-tests
  - ./familyline-tests
