language: cpp
dist: focal
compiler:
  - gcc

os:
  - linux
  
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-10
      - libglm-dev
      - libglew2.1
      - libglew-dev
      - libsdl2-2.0.0
      - libfmt-dev
      - libsdl2-dev
      - libdevil1c2
      - libdevil-dev
      - libcairo2
      - libcairo2-dev
      - libyaml-0-2
      - libyaml-dev
      - libpango-1.0-0
      - libpango1.0-dev
      - libpangocairo-1.0-0
      - libflatbuffers-dev
      - flatbuffers-compiler-dev
      
env:
  - CXX=g++-10

script:
  - ${CXX} --version
  - mkdir build && cd build
  - cmake -DDO_TESTS=on -DDO_CHECK_ASAN=off -DSET_COVERAGE=off -DUSE_RELATIVE_PATH=on -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
  - make familyline-tests
  - ./familyline-tests
