language: cpp
dist: trusty
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test

    packages:
      - g++-7
      - libglm-dev
      - libglew1.10
      - libglew-dev
      - libsdl2-2.0.0
      - libsdl2-dev
      - libdevil1c2
      - libdevil-dev
      - libcairo2
      - libcairo2-dev
      - libyaml-0-2
      - libyaml-dev

script:
  - make clean
  - cmake -DDO_TESTS=on -DDO_CHECK_ASAN=off -DSET_COVERAGE=off -DUSE_RELATIVE_PATH=on -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
  - make familyline-tests
  - ./famiyline-tests
